### PR TITLE
Add support for scenarios - for #3

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @dabreegster I'm confident this is a good change but wanted to make it as a PR just to get a second pair of eyes on it so you see broadly what I'm up. This PR generalises the `ab_scenario()` function enabling different scenarios to be used, based on the assumption that the name of the scenario is in column names with mode counts, e.g. `godutch_walk`.

It's a bit rough around the edges, needs to be generalised further and made more efficient, and there is the possibility of reducing package dependencies (does it really need to import `dplyr`?) but it works :tada: 

If this package is to be future proof it will need more than 1 pair of eyes on it so a brief glance and maybe even a test for reproducibility would be appreciated. Heads-up also @joeytalbot, this is the new home of the abstr pkg and I'm hoping to improve the R/A/B street interface over time.

**Comment by dabreegster** [comment]
I glanced at the diff and don't spot anything amiss, but I also basically don't know R. :)

I have a few general pieces of feedback for making this a general library. I'm not sure what R conventions are, so take these with extremely coarse grains of salt.

- Can we depend on specific versions of packages at https://github.com/a-b-street/abstr/blob/7d0f687b62a300304b6ee166fa7ab32cdb18b47b/DESCRIPTION#L12 or somewhere else? If I run this code 10 years from now, it should still do exactly the same thing, not silently break when one of the dependencies changes its API.
- There are lots of commented-out debug calls. Seems reasonable to leave these in if they're helpful for the next person developing.
- Maybe things like https://github.com/a-b-street/abstr/blob/7d0f687b62a300304b6ee166fa7ab32cdb18b47b/R/ab_scenario.R#L26 don't really have context outside of this package and should be cleaned up
- From reading the docs for the input (https://github.com/a-b-street/abstr/blob/7d0f687b62a300304b6ee166fa7ab32cdb18b47b/R/ab_scenario.R#L5), as an external user, I have no idea what shape these different inputs should have. How are counts for different modes specified? It seems tedious to document all of this; in languages I'm used to, you can define types that have a specific set of named fields, and enforce that people pass these in. What's typical with R?

The way I would model this API in my mental model would look something like this. Using vague pseudocode syntax that could be Rust or Java or who knows.

```
// Assume there's some standard Polygon and Point2D type
// Vec = just a list or sequence of something
// Map = aka dictionary, key/values
enum Mode { Drive, Bike, Walk, Transit, Other }

struct DesireLine {
  from_zone: String,
  to_zone: String,
  mode: Mode,
  number_trips: integer,
}

struct Trip {
  from_building: Point2D,
  to_building: Point2D,
  mode: Mode,
}

/// Each DesireLine describes a number of trips using a certain mode that goes from zone1 to zone2. For each /// of those trips, randomly select a building in zone1 (only using origin_buildings) and zone2 (only using /// destination_buildings) and create a Trip.
fn disaggregate_desire_lines(
  origin_buildings: Vec<Polygon>,
  destination_buildings: Vec<Polygon>,
  zones: Map<String, Polygon>,
  desire_lines: Vec<DesireLine>,
) -> Vec<Trip>
```

The user might have the DesireLine data in slightly different formats, like maybe a list of
`from_zone`, `to_zone`, `number_trips_walking`, `number_trips_cycling` tuples. But they can transform that trivially into a list of `DesireLine`s. Instead of the common library API being super flexible to a bunch of different inputs and having to specify all the rules for how it infers the shape of the data, it just takes the simplest thing.

**Comment by Robinlovelace** [comment]
Thanks for all the comments @dabreegster. The most important is on reproducibility and pinning package versions. There are various ways to do this, including a `manifest.json` file but I think the most robust may be to use the `renv` package, that allows you to create a completely reproducible environment. In fact there is a discussion of this precise topic in the `renv` issue tracker: https://github.com/rstudio/renv/issues/634

I suggest not doing this now as it will take time but have opened an issue on the topic to track progress on this: https://github.com/a-b-street/abstr/issues/5

R allows you to set minimum versions but not, as far as I can tell, precise versions. Agree that minimum versions on all packages is the way to go but, given the aspiration to reduce dependencies, I suggest adding minimum versions after fixing https://github.com/a-b-street/abstr/issues/6.

Regarding data structures, this builds on mature `sf` object that implements the Simple Features open standard from the OGC: https://geocompr.robinlovelace.net/spatial-class.html#intro-sf

The list structure is there as a pathway to get to the JSON output which is a pragmatic step that could be formalised, e.g. as an S3 or an R6 class (the latter of which behaves more like classes in other programming languages like Python as documented here https://adv-r.hadley.nz/r6.html ) but I have no immediate plans to do this given that that is essentially and export stage and the modelling can happen in well defined `sf` objects. Open to discussion about the other points and really appreciate the input that I think will make the package much stronger.

**Review by dabreegster — APPROVED** [review]
Thanks for explaining things! I'm of course fine delaying any cleanup, since we're under a deadline. I'll read through the `sf` and `r6` docs -- it's probable that this code works much closer to how I imagine the API boundary should look, and I'm just missing some understanding of the R ecosystem.

**Pull request merged**
