### PR TITLE
São Paulo examples documentation

### PR DESCRIPTION
**Pull request by lucasccdias**
I followed the `montlake_od` example and created these two files to document the São Paulo data.

### CODE REVIEW

**Review by Robinlovelace — COMMENTED** [review]
This looks good but I think there should be `.Rd` files. Have you tried documenting the package with `devtools::document()`?

**Review by Robinlovelace — COMMENTED** [review]
I'm seeing this issue, not sure what causes it:

```
> checking Rd metadata ... WARNING
  Rd files with duplicated alias 'sao_paulo_activity_df_2':
    'leeds_site_area.Rd' 'sao_paulo_activity_df_2.Rd'
  Rd files with duplicated alias 'sao_paulo_activity_df_20':
    'leeds_site_area.Rd' 'sao_paulo_activity_df_20.Rd'
```

**Comment by Robinlovelace** [comment]
Source: https://github.com/a-b-street/abstr/runs/3560706104#step:10:198

**Comment by lucasccdias** [comment]
I am currently searching for a possible solution here...

**Comment by Robinlovelace** [comment]
I know the problem: in the other datasets it says `... alias ... sao_paulo...`.

**Comment by Robinlovelace** [comment]
But the `@alias ` tag should only be used for datasets that are the same.

**Comment by Robinlovelace** [comment]
Specifically, this change should be reverted: https://github.com/a-b-street/abstr/commit/52a4b16e359a23517712aeed36cd9e197b1b27b4

**Comment by Robinlovelace** [comment]
(My fault for such poor documentation of the data from Leeds.)

**Comment by lucasccdias** [comment]
Now it seems everything is fine.

**Review by Robinlovelace — APPROVED** [review]
Great work @lucasccdias !

**Comment by natesheehan** [comment]
Nice stuff! And my apologies for grouping the Sao Paulo datasets as aliases with the Leeds dataset. Awesome work @lucasccdias

**Pull request merged**
