### PR TITLE
Suggest dplyr for vignettes

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by natesheehan** [comment]
Looks good to me - personally haven't come across `suggest` in RMarkdow, whats the different between it and `import`?

**Review by natesheehan — APPROVED** [review]
Looks good to me -however, I haven't come across this before - what is the main difference between Suggests and Imports?

**Comment by Robinlovelace** [comment]
> Looks good to me -however, I haven't come across this before - what is the main difference between Suggests and Imports?

Good question. Suggests are not installed when you install the package, they are not seen as essential, but more packages that developers of the package should have to build all vignettes and pass all tests.

**Comment by Robinlovelace** [comment]
From `?install.packages()`:

```
dependencies	
logical indicating whether to also install uninstalled packages which these packages depend on/link to/import/suggest (and so on recursively). Not used if repos = NULL. Can also be a character vector, a subset of c("Depends", "Imports", "LinkingTo", "Suggests", "Enhances").

Only supported if lib is of length one (or missing), so it is unambiguous where to install the dependent packages. If this is not the case it is ignored, with a warning.

The default, NA, means c("Depends", "Imports", "LinkingTo").
```

 
--








--

**Comment by natesheehan** [comment]
Gotcha! That's certainly handy for memory management - and one would assume the package _user_ would already have `dplyr` installed, due to its mass popularity... Great stuff 😄

**Pull request merged**
